In [40]:
# from binance import Client
# import pandas as pd
# import dateutil.relativedelta
# from datetime import datetime
# import os
# import configparser

# config = configparser.ConfigParser()
# config.read_file(open('config.cfg'))
# PUBLIC_KEY = config.get('BINANCE', 'PUBLIC_KEY')
# PRIVATE_KEY = config.get('BINANCE', 'PRIVATE_KEY')

# client = Client(PUBLIC_KEY, PRIVATE_KEY)
# if not os.path.exists('Last_Updated.txt'):
#     last_updated_time = str(datetime.now() + dateutil.relativedelta.relativedelta(months=-1))
# else:
#     with open ('Last_Updated.txt','r') as f:
#         last_updated_time = f.read()
#     # with open('Last_Updated.txt','w') as f:
#     #     f.write(str(datetime.now()))
# print(last_updated_time)
# df = pd.DataFrame()
# for coins in client.get_all_tickers():
#     if((coins["symbol"][-4:]=="BUSD")):
#         historical_data = client.get_historical_klines(
#             coins["symbol"], Client.KLINE_INTERVAL_4HOUR, start_str=last_updated_time)
#         coin_df = pd.DataFrame(historical_data,columns = ['Open Time', 'Open', 'High', 'Low', 'Close', 'Volume', 'Close Time',
#                 'Quote Asset Volume', 'Number of Trades', 'TB Base Volume', 'TB Quote Volume', 'Ignore'])
#         coin_df["COIN"]=coins["symbol"][:-4]
#         df = pd.concat([df,coin_df],axis=0)
# df['Open Time'] = pd.to_datetime(df['Open Time']/1000, unit='s')
# df['Close Time'] = pd.to_datetime(df['Close Time']/1000, unit='s')
# numeric_columns = ['Open', 'High', 'Low', 'Close', 'Volume',
#                    'Quote Asset Volume', 'TB Base Volume', 'TB Quote Volume']

# # coin_df[numeric_columns] = coin_df[numeric_columns].apply(pd.to_numeric, axis=1)

2022-11-25 04:13:58.347310

In [42]:
df[numeric_columns] = df[numeric_columns].apply(pd.to_numeric, axis=1)
df

,Open Time,Open,High,Low,Close,Volume,Close Time,Quote Asset Volume,Number of Trades,TB Base Volume,TB Quote Volume,Ignore,COIN
0,2022-11-25 08:00:00,295.80000,299.90000,294.50000,298.80000,7.692989e+04,2022-11-25 11:59:59.999000072,2.281753e+07,33426,3.617983e+04,1.073952e+07,0,BNB
1,2022-11-25 12:00:00,298.80000,306.30000,298.70000,299.90000,1.200628e+05,2022-11-25 15:59:59.999000072,3.617353e+07,54063,6.162574e+04,1.856150e+07,0,BNB
2,2022-11-25 16:00:00,299.90000,301.60000,298.60000,301.30000,4.023760e+04,2022-11-25 19:59:59.999000072,1.208027e+07,19293,1.919994e+04,5.764272e+06,0,BNB
3,2022-11-25 20:00:00,301.20000,302.70000,300.20000,300.30000,1.259280e+04,2022-11-25 23:59:59.999000072,3.794756e+06,9069,6.204594e+03,1.870350e+06,0,BNB
0,2022-11-25 08:00:00,16451.52000,16580.00000,16399.10000,16521.02000,1.966011e+04,2022-11-25 11:59:59.999000072,3.238304e+08,407500,9.972605e+03,1.642640e+08,0,BTC
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3,2022-11-25 20:00:00,0.47620,0.47710,0.47190,0.47250,2.450008e+05,2022-11-25 23:59:59.999000072,1.162667e+05,464,7.790560e+04,3.702250e+04,0,HFT
0,2022-11-25 08:00:00,0.02714,0.02753,0.02600,0.02635,1.116004e+07,2022-11-25 11:59:59.999000072,2.958227e+05,1305,5.082763e+06,1.346556e+05,0,VITE
1,2022-11-25 12:00:00,0.02650,0.02933,0.02632,0.02866,1.994106e+07,2022-11-25 15:59:59.999000072,5.597485e+05,2360,7.954803e+06,2.227830e+05,0,VITE
2,2022-11-25 16:00:00,0.02871,0.02928,0.02771,0.02832,1.291206e+07,2022-11-25 19:59:59.999000072,3.685438e+05,1934,5.320696e+06,1.518830e+05,0,VITE
3,2022-11-25 20:00:00,0.02832,0.02841,0.02800,0.02802,2.471847e+06,2022-11-25 23:59:59.999000072,6.962459e+04,287,5.481214e+05,1.547186e+04,0,VITE

In [ ]:
import pyodbc
cnxn = pyodbc.connect('DRIVER={MySQL ODBC 8.0 ANSI Driver};UID=root;Password=mosusu;Server=127.0.0.1:3307;Database=twigram;String Types=Unicode;Trusted_Connection=yes;')
print(cnxn)
cursor = cnxn.cursor()
for coins in client.get_all_tickers():
    cursor.execute("CREATE TABLE IF NOT EXISTS twigram.{}(OpenTime DATETIME,Open FLOAT(32),High FLOAT(32),Low FLOAT,Volume LONG)".format());

for index, row in coin_df.iterrows():
    # print(row.Open_Time)
    cursor.execute("INSERT INTO twigram.ETHBUSD values(?,?,?,?,?);",row.Open_Time,row.Open,row.High,row.Low,row.Volume)
cnxn.commit()
cursor.close()

In [44]:
len(client.get_all_tickers())

2129

In [19]:
from binance import Client
import pandas as pd
import dateutil.relativedelta
from datetime import datetime
import os
import configparser

config = configparser.ConfigParser()
config.read_file(open('config.cfg'))
PUBLIC_KEY = config.get('BINANCE', 'PUBLIC_KEY')
PRIVATE_KEY = config.get('BINANCE', 'PRIVATE_KEY')

client = Client(PUBLIC_KEY, PRIVATE_KEY)
df = pd.DataFrame()

for coins in client.get_all_tickers():
    if((coins["symbol"][-4:]=="BUSD")):
        historical_data = client.get_klines(symbol=coins["symbol"],interval=Client.KLINE_INTERVAL_4HOUR,limit=1)
        coin_df = pd.DataFrame(historical_data,columns = ['Open Time', 'Open', 'High', 'Low', 'Close', 'Volume', 'Close Time','Quote Asset Volume', 'Number of Trades', 'TB Base Volume', 'TB Quote Volume', 'Ignore'])
        coin_df["COIN"]=coins["symbol"][:-4]
        df = pd.concat([df,coin_df[["Open Time","High","Low","COIN"]]],axis=0)
df['Open Time'] = pd.to_datetime(df['Open Time']/1000, unit='s')
# df['Close Time'] = pd.to_datetime(df['Close Time']/1000, unit='s')
# numeric_columns = ['Open', 'High', 'Low', 'Close', 'Volume',
#                    'Quote Asset Volume', 'TB Base Volume', 'TB Quote Volume']

In [17]:
df[numeric_columns] = df[numeric_columns].apply(pd.to_numeric, axis=1)

In [20]:
df

             Open Time            High             Low    COIN
0  2022-11-27 20:00:00    314.20000000    311.20000000     BNB
0  2022-11-27 20:00:00  16574.91000000  16538.08000000     BTC
0  2022-11-27 20:00:00      0.40400000      0.40150000     XRP
0  2022-11-27 20:00:00   1216.01000000   1211.31000000     ETH
0  2019-11-28 00:00:00    221.64000000    219.78000000  BCHABC
..                 ...             ...             ...     ...
0  2022-11-27 20:00:00      4.76580000      4.70110000     APT
0  2022-11-27 20:00:00      0.00904200      0.00893500     QKC
0  2022-11-27 20:00:00      1.03100000      1.02000000    OSMO
0  2022-11-27 20:00:00      0.54950000      0.50020000     HFT
0  2022-11-27 20:00:00      0.02656000      0.02586000    VITE

[373 rows x 4 columns]